'''4) Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
a. 0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
b. By considering the terms in the Fibonacci sequence whose values do not exceed
four hundred, find the sum of the even-valued terms.
'''
num=int(input("enter how many fibonacci series number is display:"))
f0=1
f1=1
print("Terms of fibonaccie series is:")
print(f0,f1)
i=2
while i < num:
       f=f0+f1
       f0=f1
       f1=f
       print(f)
       i=i+1
